name: Example Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened
    branches:
      - main

jobs:
  always-run:
    runs-on: ubuntu-latest
    steps:
      - name: Run always
        run: echo "This runs on every trigger"

  skip-on-pr:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Run only outside PR events
        run: echo "This does NOT run on PR create/update/merge"
